apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: flqb963ko-go 
  janus-idp.io/tekton: flqb963ko-go
  backstage.io/kubernetes-id: flqb963ko-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flqb963ko-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  