apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flqb963ko-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flqb963ko-go 
  name: flqb963ko-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: flqb963ko-go 
